version: '3.8'

services:
  # Main application
  helpdesk-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./helpdesk.db
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2:14b
      - CHROMA_PERSIST_DIRECTORY=./chroma_db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./chroma_db:/app/chroma_db
    depends_on:
      - ollama
    networks:
      - helpdesk-network

  # Streamlit UI
  helpdesk-ui:
    build: .
    command: streamlit run app/ui/chat_interface.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_BASE=http://helpdesk-api:8000
    depends_on:
      - helpdesk-api
    networks:
      - helpdesk-network

  # Dashboard
  helpdesk-dashboard:
    build: .
    command: streamlit run app/ui/dashboard.py --server.port=8502 --server.address=0.0.0.0
    ports:
      - "8502:8502"
    environment:
      - API_BASE=http://helpdesk-api:8000
    depends_on:
      - helpdesk-api
    networks:
      - helpdesk-network

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - helpdesk-network

volumes:
  ollama_data:

networks:
  helpdesk-network:
    driver: bridge